---
- name: Download Java
  command: >
    wget -q -O "{{ java_archive }}" --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' "{{ download_url }}"
    creates={{ java_archive }}

- name: Install Java
  yum: > 
    name={{ java_archive }}
    state=present
